name: test_flutter_claude_code_test3
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  http: ^1.6.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.2.1

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.7.1
  json_serializable: ^6.11.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "111111"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#111111"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
