name: test_flutter_claude_code_test3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod:
  http:
  freezed_annotation:
  json_annotation:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  freezed:
  build_runner:
  json_serializable:
  riverpod_generator:

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "111111"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#111111"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
